# Manually generated by Lucky Nkosi 5.2.1 on 2025-05-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curator_app', '0001_initial'),
    ]

    operations = [
    ]
