# Manually generated by Lucky Nkosi on 2025-05-24 12:51

import os
from django.db import migrations
from django.contrib.auth import get_user_model

def create_superuser(apps, schema_editor):
    """
    Creates a superuser using environment variables.
    """
    User = get_user_model()
    
    # Get credentials from environment variables
    username = os.environ.get('ADMIN_USER')
    email = os.environ.get('ADMIN_EMAIL')
    password = os.environ.get('ADMIN_PASSWORD')

    # Check for missing environment variables
    if not all([username, email, password]):
        print("\nAdmin user environment variables not set. Skipping superuser creation.")
        return

    # Check if username exists
    if User.objects.filter(username=username).exists():
        print(f"\nSuperuser '{username}' already exists. Skipping.")
        return

    # Create superuser
    print(f"\nCreating superuser '{username}'...")
    User.objects.create_superuser(
        username=username,
        email=email,
        password=password
    )
    print("Superuser created successfully.")

class Migration(migrations.Migration):

    dependencies = [
        # That other migration file
        ('curator_app', '0001_initial'), 
    ]

    operations = [
        # Let's operate!
        migrations.RunPython(create_superuser),
    ]